export const ipcCommands = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SHOW_AUTH_SCREEN: 'SHOW_AUTH_SCREEN',
  START_PLAYER: 'START_PLAYER',
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
} as const;