export const ipcCommands = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SHOW_AUTH_SCREEN: 'SHOW_AUTH_SCREEN',
  START_PLAYER: 'START_PLAYER',
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
  UPDATE_CONNECTION_MODE: 'UPDATE_CONNECTION_MODE',
  UPDATE_AVAILABLE_MASTERS: 'UPDATE_AVAILABLE_MASTERS',
  UPDATE_SELECTED_MASTER: 'UPDATE_SELECTED_MASTER',
  RESET_DATA: 'RESET_DATA',
} as const;
